Fp3 solid
platais/flight-planner-dotnet pull request #3
Opened 2020-10-07 14:16 UTC by platais

Sākotnēji sajaucos ar failu struktūru, iepušoju, pēc tam sapratu, ka viss slikti, Git tīrības ziņā, ti.

2020-10-10 17:22 UTC, ausmoons requested changes

2020-10-10 17:22 UTC, ausmoons commented on FlightPlanner3/FlightPlanner3/Controllers/CustomerController.cs
> +            //varetu parplanot sis divas metodes - atrasanas vietu...
?

2020-10-11 14:20 UTC, platais commented on FlightPlanner3/Flight-Planner.Core/Models/Airport.cs
> +            }
done

2020-10-11 14:21 UTC, platais commented on FlightPlanner3/Flight-Planner.Core/Models/Flight.cs
> +
done

2020-10-11 14:22 UTC, platais commented on FlightPlanner3/Flight-Planner.Core/Models/Flight.cs
> +            if (obj == null)
ok, done. This code was from very first version :)

2020-10-11 14:27 UTC, platais commented on FlightPlanner3/Flight-Planner.Data/FlightPlannerDbContext.cs
> +            //Database.SetInitializer<FlightPlannerDbContext>(null);
Paldies, PR palika, jo negribēju dzēst, lai vel izprašņātu par šo, tagad notīriju.

2020-10-11 14:29 UTC, platais commented on FlightPlanner3/Flight-Planner.Data/Migrations/Configuration.cs
> +            //  This method will be called after migrating to the latest version.
Nop, it was like that, autogenerated, so I didn't touch these comments either.

2020-10-11 14:34 UTC, platais commented on FlightPlanner3/Flight-Planner.Services/AirportService.cs
> +            throw new NotImplementedException();
Interfeisu airporta servisam taisiju copy-paste no iFlightService , atstaju to ,kas varbūt noderēs , nenoderēja, atsevišķi tāpat airportu nav jēga dzēst, nedzēšot flaitu, bet pieliku funkcionalitāti vismaz, lai nestāv Exc te.

2020-10-11 14:36 UTC, platais commented on FlightPlanner3/FlightPlanner3/Controllers/CustomerController.cs
> +            //varetu parplanot sis divas metodes - atrasanas vietu...
Nepietika drosmes un laika. Aizvācu komentāru.

2020-10-12 19:17 UTC, ausmoons approved these changes
Pirms merge, sagaidi Edgara review

2021-06-02 18:01 UTC, merged